---
title: "Eating Clubs"
output: html_document
date: "2022-11-06"
---

```{=html}
<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Vertical dashed lines highlight Spring semester Dean's Dates. The red dashed line highlights the 2018 university-wide consent pledge intervention.

Double-click an infraction type on the legend on the right to see data for only that infraction type.

-   **sex_harm:** infractions that were coded as both sex & harm

-   **null:** infractions that were neither sex, harm, or party

```{r code, echo = FALSE, results = FALSE, message=FALSE, warning=FALSE}

#loading relevant libraries
library(tidyverse)
library(lubridate)
library(plotly)
library(plyr)
library(lemon)
library(ggforce)
library(tufte)
library("writexl")

#load data
alldata <- read.csv("eclub_all_AD.csv")

#create a null variable
alldata <- alldata |> 
  mutate(null = if_else(alldata$sex == 0 & alldata$harm == 0 & alldata$party == 0, 1, 0))

#standardize the dates
alldata <- alldata |> 
  mutate(infr_date = mdy(infr_date))

#create a Dean's Date variable
deans_date_dates <- as.Date(c("2008-05-13", "2009-05-12", "2010-05-11", "2011-05-10", 
                              "2012-05-15", "2013-05-14", "2014-05-13", "2015-05-12", 
                              "2016-05-10", "2017-05-16", "2018-05-15", "2019-05-14", "2020-05-12"))

deans_date_df <- data.frame(infr_date = deans_date_dates)

alldata <- alldata |> 
  mutate(deans_date = case_when(
    alldata$infr_date %in% deans_date_dates ~ 1,
    TRUE ~ 0
  ))

#correct the values for the year variable
alldata <- alldata |> 
  mutate(year = str_sub(infr_date, 1, 4))

#create a month variable
alldata <- alldata |> 
  mutate(month = month(infr_date, label = TRUE))

#create a semester variable
alldata <- alldata |> 
  mutate(semester = case_when(
    month %in% c("Jan", "Feb", "Mar", "Apr", "May") ~ "Spring",
    month %in% c("Jun", "Jul", "Aug") ~ "Summer",
    TRUE ~ "Fall"
  ))
unique(alldata$semester)

#create a variable for semester + year
alldata <-  alldata |> 
  mutate(term = str_c(semester, year, sep = " "))
unique(alldata$term)

#create a variable for month + year
alldata <-  alldata |> 
  mutate(month_year = str_c(month, year, sep = " "))
unique(alldata$month_year)

#factorize
alldata$harm <- factor(alldata$harm)
alldata$sex <- factor(alldata$sex)
alldata$party <- factor(alldata$party)
alldata$term <- factor(alldata$term)
alldata$null <- factor(alldata$null)
alldata$deans_date <- factor(alldata$deans_date)

levels(alldata$harm)
levels(alldata$sex)
levels(alldata$party)
levels(alldata$term)
levels(alldata$null)
levels(alldata$deans_date)

glimpse(alldata)

#arrange by date
alldata <- alldata |> 
  arrange(infr_date)

alldata$term <- reorder(alldata$term, alldata$infr_date)
alldata$month_year <- reorder(alldata$month_year, alldata$infr_date)

#remove 1 data point from 2006
alldata <- alldata |> 
  filter(year != 2006)
unique(alldata$year)

#remove Summer semester
alldata <- alldata |> 
  filter(semester != "Summer") |> 
  droplevels()
levels(alldata$term)

alldata_clean <- write.csv(alldata,"alldata_clean.csv")

#### Look at data for every day in May for 2008-2019

#filter filler data
filler <- c(seq(as.Date("2008-01-01"), as.Date("2008-05-31"), by = "days"),
            seq(as.Date("2009-01-01"), as.Date("2009-05-31"), by = "days"),
            seq(as.Date("2010-01-01"), as.Date("2010-05-31"), by = "days"),
            seq(as.Date("2011-01-01"), as.Date("2011-05-31"), by = "days"),
            seq(as.Date("2012-01-01"), as.Date("2012-05-31"), by = "days"),
            seq(as.Date("2013-01-01"), as.Date("2013-05-31"), by = "days"),
            seq(as.Date("2014-01-01"), as.Date("2014-05-31"), by = "days"),
            seq(as.Date("2015-01-01"), as.Date("2015-05-31"), by = "days"),
            seq(as.Date("2016-01-01"), as.Date("2016-05-31"), by = "days"),
            seq(as.Date("2017-01-01"), as.Date("2017-05-31"), by = "days"),
            seq(as.Date("2018-01-01"), as.Date("2018-05-31"), by = "days"),
            seq(as.Date("2019-01-01"), as.Date("2019-05-31"), by = "days"))

filler_data <- data.frame(infr_date = filler)

table(filler %in% alldata$infr_date)

#make a table with total # of infractions by type
all <- alldata |> 
  group_by(infr_date) |> 
  dplyr::summarise(all = n())

all <- merge(all, filler_data, by = "infr_date", all.x = TRUE, all.y = TRUE)

sex <- alldata[alldata$sex == 1, ] |> 
  group_by(infr_date) |> 
  dplyr::summarise(sex = n())

sex <- merge(sex, filler_data, by = "infr_date", all.x = TRUE, all.y = TRUE)

harm <- alldata[alldata$harm == 1, ] |> 
  group_by(infr_date) |> 
  dplyr::summarise(harm = n())

harm <- merge(harm, filler_data, by = "infr_date", all.x = TRUE, all.y = TRUE)

sex_harm <- alldata[alldata$sex == 1 & alldata$harm == 1, ] |> 
  group_by(infr_date) |> 
  dplyr::summarise(sex_harm = n())

sex_harm <- merge(sex_harm, filler_data, by = "infr_date", all.x = TRUE, all.y = TRUE)

party <- alldata[alldata$party == 1, ] |> 
  group_by(infr_date) |> 
  dplyr::summarise(party = n())

party <- merge(party, filler_data, by = "infr_date", all.x = TRUE, all.y = TRUE)

null <- alldata[alldata$null == 1, ] |> 
  group_by(infr_date) |> 
  dplyr::summarise(null = n())

null <- merge(null, filler_data, by = "infr_date", all.x = TRUE, all.y = TRUE)

everything <- full_join(all, sex, by = "infr_date")
everything <- full_join(everything, harm, by = "infr_date")
everything <- full_join(everything, sex_harm, by = "infr_date")
everything <- full_join(everything, party, by = "infr_date")
everything <- full_join(everything, null, by = "infr_date")

#convert NAs to 0s
everything[is.na(everything)] <- 0

#convert into tidy format
everything_tidy <- everything |> 
  pivot_longer(names_to = "infr_type",
               values_to = "total",
               cols = -infr_date)

#add a column for year
everything_tidy <- everything_tidy |> 
  mutate(year = year(infr_date))

#add a column for month
everything_tidy <- everything_tidy |> 
  mutate(month = month(infr_date, label = TRUE))

#add a column for day
everything_tidy <- everything_tidy |> 
  mutate(day = day(infr_date))

#create a semester variable
everything_tidy <- everything_tidy |> 
  mutate(semester = case_when(
    month %in% c("Jan", "Feb", "Mar", "Apr", "May") ~ "Spring",
    month %in% c("Jun", "Jul", "Aug") ~ "Summer",
    TRUE ~ "Fall"
  ))
unique(everything_tidy$semester)

#remove 2020
everything_tidy <- everything_tidy |> 
  filter(year != 2020)

#plot the data
plot_month <- everything_tidy[everything_tidy$month == "May", ] |> 
  ggplot(aes(y = total, x = day, color = infr_type, group = infr_type)) +
  theme(axis.text.x = element_text(angle = 90, size = 7)) +
  geom_point(size = 1) +
  geom_line() +
  facet_rep_wrap(~ year, repeat.tick.labels = TRUE, scales = "free_x") +
  scale_y_continuous(limits = c(0, 20), breaks = seq(0, 20, by = 1)) +
  scale_x_continuous(breaks = seq(0, 31, by = 1)) +
  labs(title = "Campus police data 2008-2019: month of May by day",
       x = "Day of Month", 
       y = "Number of infractions",
       subtitle = "Vertical dashed lines highlight Spring semester Dean's Dates. The red dashed line highlights the 2018 university-wide consent pledge intervention.",
       color = "Infraction type")

plot_month <- plot_month + 
  geom_vline(data = filter(everything_tidy, year == 2008), aes(xintercept=13), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2009), aes(xintercept=12), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2010), aes(xintercept=11), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2011), aes(xintercept=10), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2012), aes(xintercept=15), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2013), aes(xintercept=14), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2014), aes(xintercept=13), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2015), aes(xintercept=12), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2016), aes(xintercept=10), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2017), aes(xintercept=16), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2018), aes(xintercept=15), linetype = "dashed", colour = "red") +
  geom_vline(data = filter(everything_tidy, year == 2019), aes(xintercept=14), linetype = "dashed")

plotly_month <- ggplotly(plot_month, dynamicTicks = FALSE)

### Plot the data for Spring Semester 2008-2019

everything_tidy <- everything_tidy |> 
  filter(semester == "Spring")

#plot the data
plot_month1int <- everything_tidy[everything_tidy$year == 2008, ] |> 
  ggplot(aes(y = total, x = infr_date, color = infr_type, group = infr_type)) +
  theme(axis.text.x = element_text(angle = 90, size = 7)) +
  theme(axis.text.y = element_text(size = 5)) +
  geom_point(size = 1) +
  geom_line() +
  #facet_rep_wrap(~ year, repeat.tick.labels = TRUE, nrow = 3, ncol = 1, scales = "free_x") +
  #facet_wrap_paginate(~ year, nrow = 3, ncol = 1, scales = "free_x", page = 1) +
  scale_x_date(date_labels = "%d %b", date_breaks = "1 day", expand = c(0,0)) +
  scale_y_continuous(limits = c(0, 40), breaks = seq(0, 40, by = 1)) +
  labs(title = "Campus police data: Spring 2008",
       x = "Day", 
       y = "Number of infractions",
       caption = "Vertical dashed lines highlight Spring semester Dean's Dates.",
       color = "Infraction type")

plot_month1int <- plot_month1int + 
  geom_vline(data = filter(everything_tidy, year == 2008), aes(xintercept=as.numeric(everything_tidy$infr_date[799])), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2009), aes(xintercept=as.numeric(everything_tidy$infr_date[1699])), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2010), aes(xintercept=as.numeric(everything_tidy$infr_date[2599])), linetype = "dashed")

plotly_month1int <- ggplotly(plot_month1int, height = 300)

#plot the data
plot_month1.1int <- everything_tidy[everything_tidy$year == 2009, ] |> 
  ggplot(aes(y = total, x = infr_date, color = infr_type, group = infr_type)) +
  theme(axis.text.x = element_text(angle = 90, size = 7)) +
  theme(axis.text.y = element_text(size = 5)) +
  geom_point(size = 1) +
  geom_line() +
  #facet_rep_wrap(~ year, repeat.tick.labels = TRUE, nrow = 3, ncol = 1, scales = "free_x") +
  #facet_wrap_paginate(~ year, nrow = 3, ncol = 1, scales = "free_x", page = 1) +
  scale_x_date(date_labels = "%d %b", date_breaks = "1 day", expand = c(0,0)) +
  scale_y_continuous(limits = c(0, 40), breaks = seq(0, 40, by = 1)) +
  labs(title = "Campus police data: Spring 2009",
       x = "Day", 
       y = "Number of infractions",
       caption = "Vertical dashed lines highlight Spring semester Dean's Dates.",
       color = "Infraction type")

plot_month1.1int <- plot_month1.1int + 
  geom_vline(data = filter(everything_tidy, year == 2008), aes(xintercept=as.numeric(everything_tidy$infr_date[799])), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2009), aes(xintercept=as.numeric(everything_tidy$infr_date[1699])), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2010), aes(xintercept=as.numeric(everything_tidy$infr_date[2599])), linetype = "dashed")

plotly_month1.1int <- ggplotly(plot_month1.1int, height = 300)

#plot the data
plot_month1.2int <- everything_tidy[everything_tidy$year == 2010, ] |> 
  ggplot(aes(y = total, x = infr_date, color = infr_type, group = infr_type)) +
  theme(axis.text.x = element_text(angle = 90, size = 7)) +
  theme(axis.text.y = element_text(size = 5)) +
  geom_point(size = 1) +
  geom_line() +
  #facet_rep_wrap(~ year, repeat.tick.labels = TRUE, nrow = 3, ncol = 1, scales = "free_x") +
  #facet_wrap_paginate(~ year, nrow = 3, ncol = 1, scales = "free_x", page = 1) +
  scale_x_date(date_labels = "%d %b", date_breaks = "1 day", expand = c(0,0)) +
  scale_y_continuous(limits = c(0, 40), breaks = seq(0, 40, by = 1)) +
  labs(title = "Campus police data: Spring 2010",
       x = "Day", 
       y = "Number of infractions",
       caption = "Vertical dashed lines highlight Spring semester Dean's Dates.",
       color = "Infraction type")

plot_month1.2int <- plot_month1.2int + 
  geom_vline(data = filter(everything_tidy, year == 2008), aes(xintercept=as.numeric(everything_tidy$infr_date[799])), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2009), aes(xintercept=as.numeric(everything_tidy$infr_date[1699])), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2010), aes(xintercept=as.numeric(everything_tidy$infr_date[2599])), linetype = "dashed")

plotly_month1.2int <- ggplotly(plot_month1.2int, height = 300)

#plot the data
plot_month2int <- everything_tidy[everything_tidy$year == 2011, ] |> 
  ggplot(aes(y = total, x = infr_date, color = infr_type, group = infr_type)) +
  theme(axis.text.x = element_text(angle = 90, size = 7)) +
  theme(axis.text.y = element_text(size = 5)) +
  geom_point(size = 1) +
  geom_line() +
  #facet_rep_wrap(~ year, repeat.tick.labels = TRUE, nrow = 3, ncol = 1, scales = "free_x") +
  #facet_wrap_paginate(~ year, nrow = 3, ncol = 1, scales = "free_x", page = 2) +
  scale_x_date(date_labels = "%d %b", date_breaks = "1 day", expand = c(0,0)) +
  scale_y_continuous(limits = c(0, 40), breaks = seq(0, 40, by = 1)) +
  labs(title = "Campus police data: Spring 2011",
       x = "Day", 
       y = "Number of infractions",
       caption = "Vertical dashed lines highlight Spring semester Dean's Dates.",
       color = "Infraction type")

plot_month2int <- plot_month2int + 
  geom_vline(data = filter(everything_tidy, year == 2011), aes(xintercept=as.numeric(everything_tidy$infr_date[3499])), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2012), aes(xintercept=as.numeric(everything_tidy$infr_date[4441])), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2013), aes(xintercept=as.numeric(everything_tidy$infr_date[5341])), linetype = "dashed")

plotly_month2int <- ggplotly(plot_month2int, height = 300)

#plot the data
plot_month2.1int <- everything_tidy[everything_tidy$year == 2012, ] |> 
  ggplot(aes(y = total, x = infr_date, color = infr_type, group = infr_type)) +
  theme(axis.text.x = element_text(angle = 90, size = 7)) +
  theme(axis.text.y = element_text(size = 5)) +
  geom_point(size = 1) +
  geom_line() +
  #facet_rep_wrap(~ year, repeat.tick.labels = TRUE, nrow = 3, ncol = 1, scales = "free_x") +
  #facet_wrap_paginate(~ year, nrow = 3, ncol = 1, scales = "free_x", page = 2) +
  scale_x_date(date_labels = "%d %b", date_breaks = "1 day", expand = c(0,0)) +
  scale_y_continuous(limits = c(0, 40), breaks = seq(0, 40, by = 1)) +
  labs(title = "Campus police data: Spring 2012",
       x = "Day", 
       y = "Number of infractions",
       caption = "Vertical dashed lines highlight Spring semester Dean's Dates.",
       color = "Infraction type")

plot_month2.1int <- plot_month2.1int + 
  geom_vline(data = filter(everything_tidy, year == 2011), aes(xintercept=as.numeric(everything_tidy$infr_date[3499])), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2012), aes(xintercept=as.numeric(everything_tidy$infr_date[4441])), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2013), aes(xintercept=as.numeric(everything_tidy$infr_date[5341])), linetype = "dashed")

plotly_month2.1int <- ggplotly(plot_month2.1int, height = 300)

#plot the data
plot_month2.2int <- everything_tidy[everything_tidy$year == 2013, ] |> 
  ggplot(aes(y = total, x = infr_date, color = infr_type, group = infr_type)) +
  theme(axis.text.x = element_text(angle = 90, size = 7)) +
  theme(axis.text.y = element_text(size = 5)) +
  geom_point(size = 1) +
  geom_line() +
  #facet_rep_wrap(~ year, repeat.tick.labels = TRUE, nrow = 3, ncol = 1, scales = "free_x") +
  #facet_wrap_paginate(~ year, nrow = 3, ncol = 1, scales = "free_x", page = 2) +
  scale_x_date(date_labels = "%d %b", date_breaks = "1 day", expand = c(0,0)) +
  scale_y_continuous(limits = c(0, 40), breaks = seq(0, 40, by = 1)) +
  labs(title = "Campus police data: Spring 2013",
       x = "Day", 
       y = "Number of infractions",
       caption = "Vertical dashed lines highlight Spring semester Dean's Dates.",
       color = "Infraction type")

plot_month2.2int <- plot_month2.2int + 
  geom_vline(data = filter(everything_tidy, year == 2011), aes(xintercept=as.numeric(everything_tidy$infr_date[3499])), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2012), aes(xintercept=as.numeric(everything_tidy$infr_date[4441])), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2013), aes(xintercept=as.numeric(everything_tidy$infr_date[5341])), linetype = "dashed")

plotly_month2.2int <- ggplotly(plot_month2.2int, height = 300)

#plot the data
plot_month3int <- everything_tidy[everything_tidy$year == 2014, ] |> 
  ggplot(aes(y = total, x = infr_date, color = infr_type, group = infr_type)) +
  theme(axis.text.x = element_text(angle = 90, size = 7)) +
  theme(axis.text.y = element_text(size = 5)) +
  geom_point(size = 1) +
  geom_line() +
  #facet_rep_wrap(~ year, repeat.tick.labels = TRUE, nrow = 3, ncol = 1, scales = "free_x") +
  #facet_wrap_paginate(~ year, nrow = 3, ncol = 1, scales = "free_x", page = 3) +
  scale_x_date(date_labels = "%d %b", date_breaks = "1 day", expand = c(0,0)) +
  scale_y_continuous(limits = c(0, 40), breaks = seq(0, 40, by = 1)) +
  labs(title = "Campus police data: Spring 2014",
       x = "Day", 
       y = "Number of infractions",
       caption = "Vertical dashed lines highlight Spring semester Dean's Dates.",
       color = "Infraction type")

plot_month3int <- plot_month3int + 
  geom_vline(data = filter(everything_tidy, year == 2014), aes(xintercept=as.numeric(everything_tidy$infr_date[6241])), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2015), aes(xintercept=as.numeric(everything_tidy$infr_date[7141])), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2016), aes(xintercept=as.numeric(everything_tidy$infr_date[8041])), linetype = "dashed")

plotly_month3int <- ggplotly(plot_month3int, height = 300)

#plot the data
plot_month3.1int <- everything_tidy[everything_tidy$year == 2015, ] |> 
  ggplot(aes(y = total, x = infr_date, color = infr_type, group = infr_type)) +
  theme(axis.text.x = element_text(angle = 90, size = 7)) +
  theme(axis.text.y = element_text(size = 5)) +
  geom_point(size = 1) +
  geom_line() +
  #facet_rep_wrap(~ year, repeat.tick.labels = TRUE, nrow = 3, ncol = 1, scales = "free_x") +
  #facet_wrap_paginate(~ year, nrow = 3, ncol = 1, scales = "free_x", page = 3) +
  scale_x_date(date_labels = "%d %b", date_breaks = "1 day", expand = c(0,0)) +
  scale_y_continuous(limits = c(0, 40), breaks = seq(0, 40, by = 1)) +
  labs(title = "Campus police data: Spring 2015",
       x = "Day", 
       y = "Number of infractions",
       caption = "Vertical dashed lines highlight Spring semester Dean's Dates.",
       color = "Infraction type")

plot_month3.1int <- plot_month3.1int + 
  geom_vline(data = filter(everything_tidy, year == 2014), aes(xintercept=as.numeric(everything_tidy$infr_date[6241])), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2015), aes(xintercept=as.numeric(everything_tidy$infr_date[7141])), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2016), aes(xintercept=as.numeric(everything_tidy$infr_date[8041])), linetype = "dashed")

plotly_month3.1int <- ggplotly(plot_month3.1int, height = 300)

#plot the data
plot_month3.2int <- everything_tidy[everything_tidy$year == 2016, ] |> 
  ggplot(aes(y = total, x = infr_date, color = infr_type, group = infr_type)) +
  theme(axis.text.x = element_text(angle = 90, size = 7)) +
  theme(axis.text.y = element_text(size = 5)) +
  geom_point(size = 1) +
  geom_line() +
  #facet_rep_wrap(~ year, repeat.tick.labels = TRUE, nrow = 3, ncol = 1, scales = "free_x") +
  #facet_wrap_paginate(~ year, nrow = 3, ncol = 1, scales = "free_x", page = 3) +
  scale_x_date(date_labels = "%d %b", date_breaks = "1 day", expand = c(0,0)) +
  scale_y_continuous(limits = c(0, 40), breaks = seq(0, 40, by = 1)) +
  labs(title = "Campus police data: Spring 2016",
       x = "Day", 
       y = "Number of infractions",
       caption = "Vertical dashed lines highlight Spring semester Dean's Dates.",
       color = "Infraction type")

plot_month3.2int <- plot_month3.2int + 
  geom_vline(data = filter(everything_tidy, year == 2014), aes(xintercept=as.numeric(everything_tidy$infr_date[6241])), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2015), aes(xintercept=as.numeric(everything_tidy$infr_date[7141])), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2016), aes(xintercept=as.numeric(everything_tidy$infr_date[8041])), linetype = "dashed")

plotly_month3.2int <- ggplotly(plot_month3.2int, height = 300)

#plot the data
plot_month4int <- everything_tidy[everything_tidy$year == 2017, ] |> 
  ggplot(aes(y = total, x = infr_date, color = infr_type, group = infr_type)) +
  theme(axis.text.x = element_text(angle = 90, size = 7)) +
  theme(axis.text.y = element_text(size = 5)) +
  geom_point(size = 1) +
  geom_line() +
  #facet_rep_wrap(~ year, repeat.tick.labels = TRUE, nrow = 3, ncol = 1, scales = "free_x") +
  #facet_wrap_paginate(~ year, nrow = 3, ncol = 1, scales = "free_x", page = 4) +
  scale_x_date(date_labels = "%d %b", date_breaks = "1 day", expand = c(0,0)) +
  scale_y_continuous(limits = c(0, 40), breaks = seq(0, 40, by = 1)) +
  labs(title = "Campus police data: Spring 2017",
       x = "Day", 
       y = "Number of infractions",
       caption = "Vertical dashed lines highlight Spring semester Dean's Dates.",
       color = "Infraction type")

plot_month4int <- plot_month4int + 
  geom_vline(data = filter(everything_tidy, year == 2017), aes(xintercept=as.numeric(everything_tidy$infr_date[8983])), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2018), aes(xintercept=as.numeric(everything_tidy$infr_date[9883])), linetype = "dashed", colour = "red") +
  geom_vline(data = filter(everything_tidy, year == 2019), aes(xintercept=as.numeric(everything_tidy$infr_date[10783])), linetype = "dashed")

plotly_month4int <- ggplotly(plot_month4int, height = 300)

#plot the data
plot_month4.1int <- everything_tidy[everything_tidy$year == 2018, ] |> 
  ggplot(aes(y = total, x = infr_date, color = infr_type, group = infr_type)) +
  theme(axis.text.x = element_text(angle = 90, size = 7)) +
  theme(axis.text.y = element_text(size = 5)) +
  geom_point(size = 1) +
  geom_line() +
  #facet_rep_wrap(~ year, repeat.tick.labels = TRUE, nrow = 3, ncol = 1, scales = "free_x") +
  #facet_wrap_paginate(~ year, nrow = 3, ncol = 1, scales = "free_x", page = 4) +
  scale_x_date(date_labels = "%d %b", date_breaks = "1 day", expand = c(0,0)) +
  scale_y_continuous(limits = c(0, 40), breaks = seq(0, 40, by = 1)) +
  labs(title = "Campus police data: Spring 2018",
       x = "Day", 
       y = "Number of infractions",
       caption = "Vertical dashed lines highlight Spring semester Dean's Dates.  The red dashed line highlights the 2018 university-wide consent pledge intervention.",
       color = "Infraction type")

plot_month4.1int <- plot_month4.1int + 
  geom_vline(data = filter(everything_tidy, year == 2017), aes(xintercept=as.numeric(everything_tidy$infr_date[8983])), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2018), aes(xintercept=as.numeric(everything_tidy$infr_date[9883])), linetype = "dashed", colour = "red") +
  geom_vline(data = filter(everything_tidy, year == 2019), aes(xintercept=as.numeric(everything_tidy$infr_date[10783])), linetype = "dashed")

plotly_month4.1int <- ggplotly(plot_month4.1int, height = 300)

#plot the data
plot_month4.2int <- everything_tidy[everything_tidy$year == 2019, ] |> 
  ggplot(aes(y = total, x = infr_date, color = infr_type, group = infr_type)) +
  theme(axis.text.x = element_text(angle = 90, size = 7)) +
  theme(axis.text.y = element_text(size = 5)) +
  geom_point(size = 1) +
  geom_line() +
  #facet_rep_wrap(~ year, repeat.tick.labels = TRUE, nrow = 3, ncol = 1, scales = "free_x") +
  #facet_wrap_paginate(~ year, nrow = 3, ncol = 1, scales = "free_x", page = 4) +
  scale_x_date(date_labels = "%d %b", date_breaks = "1 day", expand = c(0,0)) +
  scale_y_continuous(limits = c(0, 40), breaks = seq(0, 40, by = 1)) +
  labs(title = "Campus police data: Spring 2019",
       x = "Day", 
       y = "Number of infractions",
       caption = "Vertical dashed lines highlight Spring semester Dean's Dates.",
       color = "Infraction type")

plot_month4.2int <- plot_month4.2int + 
  geom_vline(data = filter(everything_tidy, year == 2017), aes(xintercept=as.numeric(everything_tidy$infr_date[8983])), linetype = "dashed") +
  geom_vline(data = filter(everything_tidy, year == 2018), aes(xintercept=as.numeric(everything_tidy$infr_date[9883])), linetype = "dashed", colour = "red") +
  geom_vline(data = filter(everything_tidy, year == 2019), aes(xintercept=as.numeric(everything_tidy$infr_date[10783])), linetype = "dashed")

plotly_month4.2int <- ggplotly(plot_month4.2int, height = 300)

```

```{r plotly, echo=FALSE, fig.width=14, fig.height=8, fig.align='left'}

plotly_month

```

```{r plotly2, echo=FALSE, fig.width=14, fig.height=8, fig.align='left'}
plotly_month1int
plotly_month1.1int
plotly_month1.2int
plotly_month2int
plotly_month2.1int
plotly_month2.2int
plotly_month3int
plotly_month3.1int
plotly_month3.2int
plotly_month4int
plotly_month4.1int
plotly_month4.2int
```
